version: '2'

services:
    web:
        cpu_shares: 256
        mem_limit: 512m
        image: nginx:alpine
        ports:
            - "8000:80"
#        volumes:
#            - ./code:/code
#           - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        logging:
          driver: awslogs
          options: 
            awslogs-group: ecs-training
            awslogs-region: us-east-1
            awslogs-stream-prefix: web

    php:
        cpu_shares: 512
        mem_limit: 1024m
        image: php:fpm
#        volumes:
#            - ./code:/code
#            - ./log.ini:/usr/local/etc/php/conf.d/99-log.ini
        networks:
            - code-network
        logging:
          driver: awslogs
          options: 
            awslogs-group: ecs-training
            awslogs-region: us-east-1
            awslogs-stream-prefix: php

#networks:
#    code-network:
#        driver: bridge
